# -*- coding: utf-8 -*-
"""Function_Recursion.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Evv6oTC_Vzcqbr_sOGDgZveSRXyYF2wU
"""

def xyz():
   print("Print the function xyz")
def z(a,b):
  print("The Values are ",a ," and ",b)
def xyz(*par):# *par is a tupple
  print("\naccesssing the emelent using indexing")
  for i in range(len(par)):
    print(par[i],end=' ')
  return par

print("OutSide the function")
xyz()
z(4,5)
xyz("rishi","Sharma","is",3000)

z(7,8)
var1,var2,var3,var4=xyz("what","is","your","name")
print(var1,var2,var3,var4)



"""Recursion"""

def fact(n):
  if n<=1:
    return 1
  return n*fact(n-1)

fact(5)
fact(0)