# -*- coding: utf-8 -*-
"""hello.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/154EFpkU6_YXz4y601WqTwTlnEIAgHLXI
"""

print("hello")
print("hello")
print("Enter two Number")
a=int(input())
b=int(input())
result=a+b
print("Addition,division,floor division, modulo operator of two Nmber is "+str(a+b)+","+str(a/b)+","+str(a//b)+","+str(a%b)+" respectively")
#to Check even or odd number
if result%2==0:
  print(result,"is even")
else:
  print(result,"is odd")
if(a>b):
  print(a,"is greater",b)
elif(a==b):
  print(a,"is equal to ",b)
else:
  print(b,"is greater",a)

print("Enter three Number")
a=int(input())
b=int(input())
c=int(input())
print(max(a,b,c),"is the maximum number5")