# -*- coding: utf-8 -*-
"""Introductio_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bobtoVi9sSrGVOw_b5ifrBb_bGX86AGe
"""

a=10
b=-3.0
c=complex(a,b)

abs(b)

pow(a,b)
divmod(a,b)

a=5
b=10

c=a and b
print(c)
d= b and a
print(d)
e =(a>b) and b
print(e)

a=[1,2,3,[4,5,'rip'],['hello',6],45]
print(a)

for i in range(len(a)) :
  print(i,end=" ")

for i in a:
 print(i,end=" ")

a=[23,45,67]
sum=0
for i in a :
  sum+=i
print(sum)

n=int(input())
prime_flag = 0
  
if(n > 1):
    for i in range(2, n+1):
        if (n % i == 0):
            prime_flag = 1
            break
    if (prime_flag == 0):
        print("Prime")
    else:
        print("Not Prime")
else:
  print("Enter valid")

"""To find Prime Number"""

n=int(input())
prime_flag = 0
i=2
while(i<=n):
  if(n%i==0):
    prime_flag=1
    break
  else:
    i+=1
if (prime_flag==1):
  print('Not Prime')
else:
  print(' Prime')

"""To find Maximum Element in array"""

a=[12,34,56,67]
max = a[0]
for i in a:
  if i>max:
    max=i
print("max",i)

"""To find Fibonacci Number"""

n=7
f1 = 0
f2 = 1
if (n < 1):
   print("Enter valid input")
print(f1, end=" ")
for x in range(1, n):
    print(f2, end=" ")
    next = f1 + f2
    f1 = f2
    f2 = next

"""TO find quadratic eqation"""

a=int(input())
b=int(input())
c=int(input())
x=(-b+(b**2-4*a*c)**(0.5))/(2*a)
x1=(-b-(b**2-4*a*c)**(0.5))/(2*a)
print(x,x1)