# -*- coding: utf-8 -*-
"""Module_Packages(numpy,matlpot).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1k9YtNU13GsfSwfg29nRcNzQd1HPPOi7Y
"""

import numpy as np
import matplotlib.pyplot as plt

a=np.array([2,5,1,7,6,93])
print(a)
print(type(a))
print(np.__doc__)

#b=a.reshape(3,2)
print(b)#to arrange elemet in verious dimension
print(b.shape)
r=np.arange(16)
print(r)
print (np.linspace(0,10,7))

print(np.zeros(4))
print(np.ones(4))
plt.plot(a)

"""Diagonals"""

print(np.eye(2))
t=np.diag([45,33,56,78])
print(t)

"""Indexing and slicing"""

q=r.reshape(4,4)
print(q[0:3,0:4])
print(q)

"""Example:"""

a=int(input())
b=np.arange((a*a))
d=b.reshape(a,a)
print(d)

print(d[0:a//2,0:a//2])
print(d[0:a//2,a//2:a])
print(d[0])

print("Code :--")
n=int(input())
import numpy as np
a=np.arange(n*n)
a=a.reshape(n,n)
print(a[0:n//2,0:n//2])
print(a[0:n//2,n//2:n])
print(a[n//2:n,0:n//2])
print(a[n//2:n,n//2:n])