# -*- coding: utf-8 -*-
"""P1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sz3FUA02y4ANqLE8JAErOtOAkMsPe79Q
"""

paragraph=(" which is set centers on boyfriends Nick and  who sell an inherited collection of forged silver antiques to a wealthy acquaintance  Their deception quickly leads to more serious crimes, as Clay attempts to sell an expensive property that he does not fully own and Nick murders a silver appraiser who threatened to expose their sale of forgeries. The novel explores the overtourism and depopulation of Venice, and the intersection of greed, moral ambiguity, and social inequality. Critics praised Bollen's depictions of Venice and the relationships between the characters but disagreed on the effectiveness of")
paragraph_list=paragraph.split()
print("1. Word with even length :")
for i in paragraph_list:
 if(len(i)%2==0):
    print(i, end=" " )
print("\n2.Word with more than 3 vowels")    
for i in paragraph_list:
  word=i.lower()
  if ('a' in word) and ('e' in word) and ('i'in word)  :
       print(i)
  
  
  
  
#print(paragraph_list)