# -*- coding: utf-8 -*-
"""P2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jSvCPz0FCf1um02s0rCI3WAJbcYvRXGH
"""

def fibonacci(n):
  if (n<=1):
    return n
  return fibonacci(n-1)+fibonacci(n-2)

print("Enter  positive number:",end =" ")
fibo=int(input())
for i in range(fibo):
  print(fibonacci(i),end=' ')