# -*- coding: utf-8 -*-
"""P3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1N3_hj4vHr6f_2d0TZ0Gyn3BmWstyJXTR
"""

import numpy as np

def getEachElement(m,n):
  matrix=(np.arange(m*n)+2).reshape(m,n)
  for i in range(m):
    for j in range(n):
     print(matrix[i,j], end=" ")

def getEachRowAndColumn(m,n):
  matrix=(np.arange(m*n)+2).reshape(m,n)
  for i in range(m):
   print(matrix[i,0:n]) 
  for i in range(n):
   print(matrix[0:m,i])

def getCorners(m,n):
  matrix=(np.arange(m*n)+2).reshape(m,n)
  a=0 
  b=2
  for i in range(m):
     b-=a
     a-=a
     while(b<=n):
      print(i)
      print(matrix[i,a:b])
      a+=1
      b+=1
  for i in range(n):
     b-=a
     a-=a
     while(b<=m):
      print(matrix[a:b,i])
      a+=1
      b+=1

def getQuadrant(m,n):

m=int(input())
n=int(input())
matrix=(np.arange(m*n)+2).reshape(m,n)
print(matrix)
getEachElement(m,n)
getEachRowAndColumn(m,n)
getCorners(m,n)

