# -*- coding: utf-8 -*-
"""P4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VsBQI8DJjX0DyI7CZIeRVHwzRF5dVYjc
"""

import numpy as np
m=int(input())
n=int(input())



a=(np.random.default_rng()).integers(50,100,[m,n])
r=a
c=a

for i in range(n) :
  for j in range(m):
   if(j+1<n and j+1<m and i<m and i<n):
     if(r[i][j]>r[i][j+1]):
      temp=r[i][j+1]
      r[i][j+1]=r[i][j]
      r[i][i]=temp
for i in range(m) :
  for j in range(n):
   if(j+1<n and j+1 <m and i<m and i <n):
    if(c[j][i]<c[j+1][i]):
      temp=c[j+1][i]
      c[j+1][i]=c[j][i]
      c[j][i]=temp
   
print(r)
print(c)